### ISSUE TITLE
フレームワークを使う

### ISSUE THREAD

**Issue by Oni-Men** [taichi3012/ThelowDamageCalculation#12]
そろそろコンポーネントが増えてきたので、コンポーネントをファイル単位で管理したい。

**Comment by taichi3012** [comment]
そろそろ話しが実践的過ぎて追いつけなくなってきたので、自分の勉強のために質問させてもらいます。
フレームワークというのは、基本的な機能の備わった骨組みの中に、ある程度書き方が決まっている実装を書いていくってことで大丈夫ですか？

**Comment by Oni-Men** [comment]
そんな感じです。大きなWebサイト作るときに凄く便利です。

僕のリポジトリにフレームワークを使ったものがいくつかあるはずです

**Comment by taichi3012** [comment]
なるほど。リポジトリ見させてもらいます。ありがとうございます。

**Comment by Oni-Men** [comment]
デプロイの設定だけ docs にしておいてください

**Comment by taichi3012** [comment]
docsに変更しておきました。

**Comment by taichi3012** [comment]
Closeしてしまっても大丈夫ですか？
