### ISSUE TITLE
GitHub Actions使う

### ISSUE THREAD

**Issue by Oni-Men** [taichi3012/ThelowDamageCalculation#18]
GitHub Actions使うことでプッシュするだけで自動ビルド&デプロイさせたい。

[GitHub Actions による GitHub Pages への自動デプロイ](https://qiita.com/peaceiris/items/d401f2e5724fdcb0759d)
[SPA を GitHub Actions でビルドして GitHub Pages にデプロイする](https://numb86-tech.hatenablog.com/entry/2020/03/19/193413)

**Comment by taichi3012** [comment]
設定完了！

**Comment by Oni-Men** [comment]
デプロイするブランチをgh-actionsの/rootに変更できますか？

**Comment by taichi3012** [comment]
しました

**Comment by Oni-Men** [comment]
Nice!
